### ISSUE TITLE
Segfault from mnist json file when attempting to run the `backend->call` function on it

### ISSUE THREAD

**Issue by s1113950** [NervanaSystems/ngraph#1103]
Code to replicate:
```
#include <sstream>
#include <stdexcept>

#include "ngraph/file_util.hpp"
#include "ngraph/ngraph.hpp"
#include "ngraph/serializer.hpp"


using namespace std;
using namespace ngraph;

int main(int argc, char **argv)
{
    if (argc != 2) {
        throw invalid_argument("Incorrect number of arguments. Need ngraph_json only.");
    }

    const string json_string = file_util::read_file_to_string(argv[1]);
    stringstream ss(json_string);
    shared_ptr<Function> f = deserialize(ss);

    auto backend = runtime::Backend::create("CPU");

    vector<shared_ptr<runtime::TensorView>> args;
    for (shared_ptr<op::Parameter> param : f->get_parameters())
    {
        auto tensor = backend->create_tensor(param->get_element_type(), param->get_shape());
        args.push_back(tensor);
    }
    vector<shared_ptr<runtime::TensorView>> results;
    for (shared_ptr<Node> out : f->get_results())
    {
        auto result = backend->create_tensor(out->get_element_type(), out->get_shape());
        results.push_back(result);
    }
    backend->call(f, results, args);
    cout << f->get_temporary_pool_size();
}
```

Segfault:
```
Thread 1 "nprof" received signal SIGSEGV, Segmentation fault.
0x00007ffff58890b7 in _mm512_load_ps (__P=0x7fffffffd8e0) at /usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h:347
347       return *(__m512 *) __P;
(gdb) bt
#0  0x00007ffff58890b7 in _mm512_load_ps (__P=0x7fffffffd8e0) at /usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h:347
#1  Eigen::internal::pload<float __vector(16)>(Eigen::internal::unpacket_traits<float __vector(16)>::type const*) (from=0x7fffffffd8e0)
    at /ec/fm/disks/aipg_lab_home_pool_02/robertso/nprof-cpp/build/ngraph/src/ext_ngraph-build/eigen/src/Eigen/src/Core/arch/AVX512/PacketMath.h:438
#2  0x00007ffff5892a69 in Eigen::TensorEvaluator<Eigen::TensorReductionOp<Eigen::internal::MaxReducer<float>, std::array<long, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> const, Eigen::ThreadPoolDevice
>::packet<0> (this=0x7fffffffdb60, index=0) at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph-build/eigen/src/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:665
#3  0x00007ffff589083a in Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorReductionOp<Eigen::internal::MaxReducer<float>, std::array<long, 1ul> const, Eigen::TensorMap<Eigen::Tensor<flo
at, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> const> const, Eigen::ThreadPoolDevice>::evalPacket (this=0x7fffffffdb40, i=0)
    at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph-build/eigen/src/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:142
#4  0x00007ffff588e73e in Eigen::internal::EvalRange<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorReductionOp<Eigen::internal::MaxReducer<float>, std::array<long, 1ul> const, Eigen::
TensorMap<Eigen::Tensor<float, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> const> const, Eigen::ThreadPoolDevice>, long, true>::run (evaluator_in=0x7fffffffded0, first=0, last=100)
    at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph-build/eigen/src/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:118
#5  0x00007ffff588d324 in Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorReductionOp<Eigen::internal::MaxReducer<float>, std::array<long, 1ul> const, Eigen::TensorMap<Eigen::T
ensor<float, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> const> const, Eigen::ThreadPoolDevice, true>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorReductionOp<Eigen::internal::MaxRe
ducer<float>, std::array<long, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> const> const&, Eigen::ThreadPoolDevice const&)::{lambda(long, long)#1}::operator()(long, long) const (
    __closure=0x7fffffffdeb0, first=0, last=100) at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph-build/eigen/src/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:157
#6  0x00007ffff5890994 in std::_Function_handler<void (long, long), Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorReductionOp<Eigen::internal::MaxReducer<float>, std::array<l
ong, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> const> const, Eigen::ThreadPoolDevice, true>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen
::TensorReductionOp<Eigen::internal::MaxReducer<float>, std::array<long, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> const> const&, Eigen::ThreadPoolDevice const&)::{lambda(long, long)#1}>::_M_invoke(s
td::_Any_data const&, long&&, std::_Any_data const&) (__functor=..., __args#0=<unknown type in /nfs/site/home/robertso/nprof-cpp/build/ngraph/lib/libcpu_backend.so, CU 0x38237b, DIE 0x3b2e14>,
    __args#1=<unknown type in /nfs/site/home/robertso/nprof-cpp/build/ngraph/lib/libcpu_backend.so, CU 0x38237b, DIE 0x3b2e19>) at /usr/include/c++/5/functional:1871
#7  0x00007ffff57bbf15 in std::function<void (long, long)>::operator()(long, long) const (this=0x7fffffffdeb0, __args#0=0, __args#1=100) at /usr/include/c++/5/functional:2267
#8  0x00007ffff57bb44b in Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const (this=0x7ffff5cada10 <ngraph::runtime::cpu::eigen::global_thread_pool_device>, n=100, cost=...,
    block_align=..., f=...) at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph-build/eigen/src/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceThreadPool.h:181
#9  0x00007ffff588d436 in Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorReductionOp<Eigen::internal::MaxReducer<float>, std::array<long, 1ul> const, Eigen::TensorMap<Eigen::T
ensor<float, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> const> const, Eigen::ThreadPoolDevice, true>::run (expr=..., device=...)
    at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph-build/eigen/src/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:154
#10 0x00007ffff588cc70 in Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::ThreadPoolDevice>::operator=<Eigen::TensorReductionOp<Eigen::internal::MaxReducer<float>, std::array<long, 1ul> const, Eigen::TensorMap<Eigen:
:Tensor<float, 2, 1, long>, 0, Eigen::MakePointer> const, Eigen::MakePointer> > (this=0x7fffffffe030, other=...) at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph-build/eigen/src/unsupported/Eigen/CXX11/src/Tensor/TensorDevice.h:35
#11 0x00007ffff588c763 in ngraph::runtime::cpu::kernel::reduce_max<float, 2u, 1u> (input=0x15b9000, output=0x15bd000, input_shape=..., output_shape=..., reduction_axes=...)
    at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph/src/ngraph/runtime/cpu/kernel/reduce_max.hpp:86
#12 0x00007ffff588bec1 in ngraph::runtime::cpu::kernel::reduce_max_2d_1rd_float32 (input=0x15b9000, output=0x15bd000, input_shape=..., output_shape=..., reduction_axes=...)
    at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph/src/ngraph/runtime/cpu/kernel/reduce_max.cpp:50
#13 0x00007ffff7ff3484 in Function_0 ()
#14 0x00007ffff584de20 in std::_Function_handler<void (void**, void**, ngraph::runtime::cpu::CPURuntimeContext*), void (*)(void**, void**, ngraph::runtime::cpu::CPURuntimeContext*)>::_M_invoke(std::_Any_data const&, void**&&, void**&&, ngraph::runtime::cpu::CPURuntimeCo
ntext*&&) (__functor=..., __args#0=<unknown type in /nfs/site/home/robertso/nprof-cpp/build/ngraph/lib/libcpu_backend.so, CU 0x1d9363, DIE 0x2919fe>,
    __args#1=<unknown type in /nfs/site/home/robertso/nprof-cpp/build/ngraph/lib/libcpu_backend.so, CU 0x1d9363, DIE 0x291a03>, __args#2=<unknown type in /nfs/site/home/robertso/nprof-cpp/build/ngraph/lib/libcpu_backend.so, CU 0x1d9363, DIE 0x291a08>)
    at /usr/include/c++/5/functional:1871
#15 0x00007ffff57ea486 in std::function<void (void**, void**, ngraph::runtime::cpu::CPURuntimeContext*)>::operator()(void**, void**, ngraph::runtime::cpu::CPURuntimeContext*) const (this=0x963a30, __args#0=0x36912d0, __args#1=0x8f2d70, __args#2=0x93f0e0)
    at /usr/include/c++/5/functional:2267
#16 0x00007ffff57e97a5 in ngraph::runtime::cpu::CPU_CallFrame::call (this=0x963a20, output_tvs=std::vector of length 2, capacity 2 = {...}, input_tvs=std::vector of length 4, capacity 4 = {...})
    at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph/src/ngraph/runtime/cpu/cpu_call_frame.cpp:68
---Type <return> to continue, or q <return> to quit---

#17 0x00007ffff57ad941 in ngraph::runtime::cpu::CPU_Backend::call (this=0x89a340, func=std::shared_ptr (count 3, weak 0) 0x66b090, outputs=std::vector of length 2, capacity 2 = {...}, inputs=std::vector of length 4, capacity 4 = {...})
    at /nfs/site/home/robertso/nprof-cpp/build/ngraph/src/ext_ngraph/src/ngraph/runtime/cpu/cpu_backend.cpp:81
#18 0x0000000000405bcb in main (argc=2, argv=0x7fffffffe928) at THAT_BACKEND_CALL_FUNCTION_I_MENTIONED
```

Bad file:
```
[{
  "name" : "Function_0",
  "ops" : [
    {
      "element_type" : "float",
      "inputs" : [],
      "name" : "Parameter_3",
      "op" : "Parameter",
      "outputs" : ["Parameter_3_0"],
      "shape" : [ 100, 10 ]
    },
    {
      "element_type" : "float",
      "inputs" : [],
      "name" : "Parameter_2",
      "op" : "Parameter",
      "outputs" : ["Parameter_2_0"],
      "shape" : [ 100, 784 ]
    },
    {
      "element_type" : "float",
      "inputs" : [],
      "name" : "Parameter_1",
      "op" : "Parameter",
      "outputs" : ["Parameter_1_0"],
      "shape" : [10]
    },
    {
      "element_type" : "float",
      "inputs" : [],
      "name" : "Parameter_0",
      "op" : "Parameter",
      "outputs" : ["Parameter_0_0"],
      "shape" : [ 784, 10 ]
    },
    {
      "element_type" : "int32_t",
      "inputs" : [],
      "name" : "Constant_17",
      "op" : "Constant",
      "outputs" : ["Constant_17_0"],
      "shape" : [],
      "value" : ["1"]
    },
    {
      "element_type" : "int32_t",
      "inputs" : [],
      "name" : "Constant_10",
      "op" : "Constant",
      "outputs" : ["Constant_10_0"],
      "shape" : [1],
      "value" : ["100"]
    },
    {
      "element_type" : "int32_t",
      "inputs" : [],
      "name" : "Constant_26",
      "op" : "Constant",
      "outputs" : ["Constant_26_0"],
      "shape" : [],
      "value" : ["1"]
    },
    {
      "element_type" : "int32_t",
      "inputs" : [],
      "name" : "Constant_15",
      "op" : "Constant",
      "outputs" : ["Constant_15_0"],
      "shape" : [],
      "value" : ["0"]
    },
    {
      "element_type" : "float",
      "inputs" : [],
      "name" : "Constant_6",
      "op" : "Constant",
      "outputs" : ["Constant_6_0"],
      "shape" : [1],
      "value" : ["1"]
    },
    {
      "element_type" : "float",
      "inputs" : [],
      "name" : "Constant_4",
      "op" : "Constant",
      "outputs" : ["Constant_4_0"],
      "shape" : [],
      "value" : ["0"]
    },
    {
      "input_order" : [ 0, 1 ],
      "inputs" : ["Parameter_3"],
      "name" : "Reshape_48",
      "op" : "Reshape",
      "output_shape" : [ 100, 10 ],
      "outputs" : ["Reshape_48_0"]
    },
    {
      "input_order" : [ 1, 0 ],
      "inputs" : ["Parameter_2"],
      "name" : "Reshape_56",
      "op" : "Reshape",
      "output_shape" : [ 784, 100 ],
      "outputs" : ["Reshape_56_0"]
    },
    {
      "axes" : [0],
      "inputs" : ["Parameter_1"],
      "name" : "Broadcast_38",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_38_0"],
      "shape" : [ 100, 10 ]
    },
    {
      "inputs" : [ "Parameter_2", "Parameter_0" ],
      "name" : "Dot_37",
      "op" : "Dot",
      "outputs" : ["Dot_37_0"],
      "reduction_axes_count" : 1
    },
    {
      "input_order" : [],
      "inputs" : ["Constant_17"],
      "name" : "Reshape_18",
      "op" : "Reshape",
      "output_shape" : [1],
      "outputs" : ["Reshape_18_0"]
    },
    {
      "inputs" : ["Constant_10"],
      "name" : "Product_11",
      "op" : "Product",
      "outputs" : ["Product_11_0"],
      "reduction_axes" : [0]
    },
    {
      "input_order" : [0],
      "inputs" : ["Constant_6"],
      "name" : "Reshape_7",
      "op" : "Reshape",
      "output_shape" : [],
      "outputs" : ["Reshape_7_0"]
    },
    {
      "axes" : [0],
      "inputs" : ["Constant_4"],
      "name" : "Broadcast_5",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_5_0"],
      "shape" : [100]
    },
    {
      "inputs" : [ "Dot_37", "Broadcast_38" ],
      "name" : "Add_39",
      "op" : "Add",
      "outputs" : ["Add_39_0"]
    },
    {
      "axes" : [0],
      "inputs" : ["Reshape_18"],
      "name" : "Broadcast_19",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_19_0"],
      "shape" : [ 1, 1 ]
    },
    {
      "input_order" : [],
      "inputs" : ["Product_11"],
      "name" : "Reshape_12",
      "op" : "Reshape",
      "output_shape" : [1],
      "outputs" : ["Reshape_12_0"]
    },
    {
      "axes" : [0],
      "inputs" : ["Reshape_7"],
      "name" : "Broadcast_8",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_8_0"],
      "shape" : [100]
    },
    {
      "input_order" : [ 0, 1 ],
      "inputs" : ["Add_39"],
      "name" : "Reshape_40",
      "op" : "Reshape",
      "output_shape" : [ 100, 10 ],
      "outputs" : ["Reshape_40_0"]
    },
    {
      "input_order" : [ 0, 1 ],
      "inputs" : ["Broadcast_19"],
      "name" : "Reshape_20",
      "op" : "Reshape",
      "output_shape" : [],
      "outputs" : ["Reshape_20_0"]
    },
    {
      "axes" : [0],
      "inputs" : ["Reshape_12"],
      "name" : "Broadcast_13",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_13_0"],
      "shape" : [ 1, 1 ]
    },
    {
      "inputs" : [ "Broadcast_5", "Broadcast_8" ],
      "name" : "Add_9",
      "op" : "Add",
      "outputs" : ["Add_9_0"]
    },
    {
      "inputs" : ["Reshape_40"],
      "name" : "Max_41",
      "op" : "Max",
      "outputs" : ["Max_41_0"],
      "reduction_axes" : [1]
    },
    {
      "inputs" : [ "Reshape_20", "Constant_15" ],
      "name" : "Less_21",
      "op" : "Less",
      "outputs" : ["Less_21_0"]
    },
    {
      "inputs" : ["Reshape_20"],
      "name" : "Abs_24",
      "op" : "Abs",
      "outputs" : ["Abs_24_0"]
    },
    {
      "input_order" : [ 0, 1 ],
      "inputs" : ["Broadcast_13"],
      "name" : "Reshape_14",
      "op" : "Reshape",
      "output_shape" : [],
      "outputs" : ["Reshape_14_0"]
    },
    {
      "axes" : [1],
      "inputs" : ["Max_41"],
      "name" : "Broadcast_42",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_42_0"],
      "shape" : [ 100, 10 ]
    },
    {
      "inputs" : ["Reshape_14"],
      "name" : "Abs_23",
      "op" : "Abs",
      "outputs" : ["Abs_23_0"]
    },
    {
      "inputs" : [ "Reshape_14", "Constant_15" ],
      "name" : "Less_16",
      "op" : "Less",
      "outputs" : ["Less_16_0"]
    },
    {
      "inputs" : [ "Reshape_14", "Reshape_20" ],
      "name" : "Divide_30",
      "op" : "Divide",
      "outputs" : ["Divide_30_0"]
    },
    {
      "inputs" : [ "Reshape_40", "Broadcast_42" ],
      "name" : "Subtract_43",
      "op" : "Subtract",
      "outputs" : ["Subtract_43_0"]
    },
    {
      "inputs" : [ "Abs_23", "Abs_24" ],
      "name" : "Add_25",
      "op" : "Add",
      "outputs" : ["Add_25_0"]
    },
    {
      "inputs" : [ "Less_16", "Less_21" ],
      "name" : "NotEqual_22",
      "op" : "NotEqual",
      "outputs" : ["NotEqual_22_0"]
    },
    {
      "inputs" : ["Subtract_43"],
      "name" : "Exp_44",
      "op" : "Exp",
      "outputs" : ["Exp_44_0"]
    },
    {
      "inputs" : [ "Add_25", "Constant_26" ],
      "name" : "Subtract_27",
      "op" : "Subtract",
      "outputs" : ["Subtract_27_0"]
    },
    {
      "inputs" : ["Exp_44"],
      "name" : "Sum_45",
      "op" : "Sum",
      "outputs" : ["Sum_45_0"],
      "reduction_axes" : [1]
    },
    {
      "inputs" : ["Subtract_27"],
      "name" : "Negative_28",
      "op" : "Negative",
      "outputs" : ["Negative_28_0"]
    },
    {
      "axes" : [1],
      "inputs" : ["Sum_45"],
      "name" : "Broadcast_46",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_46_0"],
      "shape" : [ 100, 10 ]
    },
    {
      "inputs" : [ "Negative_28", "Abs_24" ],
      "name" : "Divide_29",
      "op" : "Divide",
      "outputs" : ["Divide_29_0"]
    },
    {
      "inputs" : [ "Exp_44", "Broadcast_46" ],
      "name" : "Divide_47",
      "op" : "Divide",
      "outputs" : ["Divide_47_0"]
    },
    {
      "inputs" : [ "NotEqual_22", "Divide_29", "Divide_30" ],
      "name" : "Select_31",
      "op" : "Select",
      "outputs" : ["Select_31_0"]
    },
    {
      "inputs" : [ "Divide_47", "Reshape_48" ],
      "name" : "Subtract_49",
      "op" : "Subtract",
      "outputs" : ["Subtract_49_0"]
    },
    {
      "inputs" : ["Select_31"],
      "name" : "Convert_32",
      "op" : "Convert",
      "outputs" : ["Convert_32_0"],
      "target_type" : "float"
    },
    {
      "axes" : [0],
      "inputs" : ["Convert_32"],
      "name" : "Broadcast_33",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_33_0"],
      "shape" : [100]
    },
    {
      "inputs" : [ "Add_9", "Broadcast_33" ],
      "name" : "Divide_34",
      "op" : "Divide",
      "outputs" : ["Divide_34_0"]
    },
    {
      "input_order" : [0],
      "inputs" : ["Divide_34"],
      "name" : "Reshape_35",
      "op" : "Reshape",
      "output_shape" : [100],
      "outputs" : ["Reshape_35_0"]
    },
    {
      "input_order" : [0],
      "inputs" : ["Reshape_35"],
      "name" : "Reshape_36",
      "op" : "Reshape",
      "output_shape" : [ 100, 1 ],
      "outputs" : ["Reshape_36_0"]
    },
    {
      "input_order" : [ 0, 1 ],
      "inputs" : ["Reshape_36"],
      "name" : "Reshape_50",
      "op" : "Reshape",
      "output_shape" : [100],
      "outputs" : ["Reshape_50_0"]
    },
    {
      "axes" : [1],
      "inputs" : ["Reshape_50"],
      "name" : "Broadcast_51",
      "op" : "Broadcast",
      "outputs" : ["Broadcast_51_0"],
      "shape" : [ 100, 10 ]
    },
    {
      "inputs" : [ "Broadcast_51", "Subtract_49" ],
      "name" : "Multiply_52",
      "op" : "Multiply",
      "outputs" : ["Multiply_52_0"]
    },
    {
      "input_order" : [ 0, 1 ],
      "inputs" : ["Multiply_52"],
      "name" : "Reshape_53",
      "op" : "Reshape",
      "output_shape" : [ 100, 10 ],
      "outputs" : ["Reshape_53_0"]
    },
    {
      "inputs" : ["Reshape_53"],
      "name" : "Sum_54",
      "op" : "Sum",
      "outputs" : ["Sum_54_0"],
      "reduction_axes" : [0]
    },
    {
      "input_order" : [ 0, 1 ],
      "inputs" : ["Reshape_53"],
      "name" : "Reshape_57",
      "op" : "Reshape",
      "output_shape" : [ 100, 10 ],
      "outputs" : ["Reshape_57_0"]
    },
    {
      "input_order" : [0],
      "inputs" : ["Sum_54"],
      "name" : "Reshape_55",
      "op" : "Reshape",
      "output_shape" : [10],
      "outputs" : ["Reshape_55_0"]
    },
    {
      "inputs" : [ "Reshape_56", "Reshape_57" ],
      "name" : "Dot_58",
      "op" : "Dot",
      "outputs" : ["Dot_58_0"],
      "reduction_axes_count" : 1
    }
  ],
  "parameters" : [ "Parameter_0", "Parameter_1", "Parameter_2", "Parameter_3" ],
  "result" : [ "Reshape_55", "Dot_58" ]
}]
```

**Comment by jbobba** [comment]
This is most likely related to an Eigen bug/issue. We have recently updated the version of Eigen that ngraph pulls from. Can you rebuild and check (after deleting your existing eigen)?

**Comment by rkimballn1** [comment]
Issue is obsolete
