### ISSUE TITLE
Install ngraph through proxy

### ISSUE THREAD

**Issue by thlinh** [NervanaSystems/ngraph#1623]
Hi,
I'm trying to install ngraph packages following instructions here https://github.com/NervanaSystems/ngraph-onnx 
But my computer is behind a company proxy, could you help me how can I install in case of a proxy server is used?
Many thanks in advance!

**Comment by rkimballn1** [comment]
Which step is giving you touble?

**Comment by thlinh** [comment]
@rkimballn1 : Thank you! I'm stucks at 
```
~/ngraph/build$ make -j 8
```
It displays errors like:

```
-- Using src='https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz'
-- Retrying...
-- Using src='https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz'
-- Retry after 5 seconds (attempt #2) ...
[ 48%] Built target ngraph
[ 49%] Built target reserialize
[ 51%] Built target ngraph_test_util
[ 52%] Built target interpreter_backend
-- Using src='https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz'
-- Retry after 15 seconds (attempt #4) ...

-- Using src='https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz'
CMake Error at ext_mkl-stamp/download-ext_mkl.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
         Uses proxy env variable https_proxy == 'https://localhost:3128/'
    Trying ::1...

  TCP_NODELAY set

  connect to ::1 port 3128 failed: Connection refused

    Trying 127.0.0.1...

  TCP_NODELAY set

  Connected to localhost (127.0.0.1) port 3128 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /home/h00472437/.conda/envs/Py36/ssl/cacert.pem
    CApath: none

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:3128

  Closing connection 0



         --- LOG END ---
         error: downloading 'https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
         Uses proxy env variable https_proxy == 'https://localhost:3128/'
    Trying ::1...

  TCP_NODELAY set

  connect to ::1 port 3128 failed: Connection refused

    Trying 127.0.0.1...

  TCP_NODELAY set

  Connected to localhost (127.0.0.1) port 3128 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /home/h00472437/.conda/envs/Py36/ssl/cacert.pem
    CApath: none

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:3128

  Closing connection 0



         --- LOG END ---
         error: downloading 'https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
         Uses proxy env variable https_proxy == 'https://localhost:3128/'
    Trying ::1...

  TCP_NODELAY set

  connect to ::1 port 3128 failed: Connection refused

    Trying 127.0.0.1...

  TCP_NODELAY set

  Connected to localhost (127.0.0.1) port 3128 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /home/h00472437/.conda/envs/Py36/ssl/cacert.pem
    CApath: none

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:3128

  Closing connection 0



         --- LOG END ---
         error: downloading 'https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
         Uses proxy env variable https_proxy == 'https://localhost:3128/'
    Trying ::1...

  TCP_NODELAY set

  connect to ::1 port 3128 failed: Connection refused

    Trying 127.0.0.1...

  TCP_NODELAY set

  Connected to localhost (127.0.0.1) port 3128 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /home/h00472437/.conda/envs/Py36/ssl/cacert.pem
    CApath: none

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:3128

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
         Uses proxy env variable https_proxy == 'https://localhost:3128/'
    Trying ::1...

  TCP_NODELAY set

  connect to ::1 port 3128 failed: Connection refused

    Trying 127.0.0.1...

  TCP_NODELAY set

  Connected to localhost (127.0.0.1) port 3128 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /home/h00472437/.conda/envs/Py36/ssl/cacert.pem
    CApath: none

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:3128

  Closing connection 0



         --- LOG END ---
         error: downloading 'https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
         Uses proxy env variable https_proxy == 'https://localhost:3128/'
    Trying ::1...

  TCP_NODELAY set

  connect to ::1 port 3128 failed: Connection refused

    Trying 127.0.0.1...

  TCP_NODELAY set

  Connected to localhost (127.0.0.1) port 3128 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /home/h00472437/.conda/envs/Py36/ssl/cacert.pem
    CApath: none

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:3128

  Closing connection 0



         --- LOG END ---




CMakeFiles/ext_mkl.dir/build.make:89: recipe for target 'mkl/src/ext_mkl-stamp/ext_mkl-download' failed
make[2]: *** [mkl/src/ext_mkl-stamp/ext_mkl-download] Error 1
CMakeFiles/Makefile2:200: recipe for target 'CMakeFiles/ext_mkl.dir/all' failed
make[1]: *** [CMakeFiles/ext_mkl.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by rkimballn1** [comment]
This may not be a proxy issue but a cmake ssl issue. Can you do
```
wget https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz
```
If that works then it is not a proxy issue. I forgot to ask, which OS are you building under? You may need to build cmake with ssl support. This is our build instructions for Centos at http://ngraph.nervanasys.com/docs/latest/buildlb.html
```
$ wget https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
$ tar -xzvf cmake-3.4.3.tar.gz
$ cd cmake-3.4.3
$ ./bootstrap --system-curl --prefix=~/cmake
$ make && make install
```
If it is not a proxy isue then build cmake and use the new cmake. You will want to delete all contents of your build directory before you run the new cmake.

**Comment by thlinh** [comment]
Hi, @rkimballn1 
Very sorry for the late answer, I was busy with other deadlines to work on this in last week. I tried your recommendations and it "seems" to be able to build the wheels. There are new 2 problems so far (By the way, my system is Ubuntu 16.4):

1. When I create the wheel with python 2.7 (our system default) and install the wheel with pip, the installation went smooth, but when running ngraph inside python 2.7, it generated error as:
```
>>> import ngraph as ng
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ngraph/__init__.py", line 18, in <module>
    from ngraph.ops import absolute
  File "ngraph/ops.py", line 20, in <module>
    from ngraph.impl import AxisSet, AxisVector, Coordinate, CoordinateDiff, Function, Node, \
  File "ngraph/impl/__init__.py", line 35, in <module>
    from _pyngraph import Function
ImportError: /usr/local/lib/python2.7/dist-packages/_pyngraph.so: undefined symbol: _ZN6ngraph11onnx_import15load_onnx_modelERSi
```
2. When I created the wheel with Python 3.6 within a Python 3.6, conda-based environment, I managed to recompile and rebuild a new wheel. But when trying to install this wheel with pip, the following error was generated:
```
ngraph-0.7.0-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.
```

Could you have a look at those problems.
Many thanks in advance!
Regards.
